# Generated by Django 3.0.2 on 2020-02-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Requeste',
        ),
    ]
